### PR TITLE
Resolve #89

### LINKED ISSUE #89: /tmp fills up causing libpng write error
When processing a large dataset, I will often set up a remote machine with a large mounted drive where the dataset is stored. `/` is only about 20GB. There are temporary files that are stored to `/tmp` so when it fills up the volume mvs-texturing will crash. Two questions:

1. Can these files be stored in a temporary folder local to the dataset?
2. Why are these temporary files so much bigger than the actual images? My images are 3-7MB but those in `/tmp` are 22-25MB. 

For reference I think the code in question is here: https://github.com/nmoehrle/mvs-texturing/blob/4fb24145a0201f7d18a1e3eb9ac2eecef624065c/libs/tex/generate_texture_views.cpp#L161

and https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L193

### PR DESCRIPTION
**Pull request by nmoehrle**

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
It needs c_str() casts and texturing.h needs updating with the added tmp parameter

**Comment by dakotabenjamin** [comment]
I think there's some issues with the mve version. I will finish testing in the morning (EST)

**Comment by nmoehrle** [comment]
I am updating mve right now, thanks for reporting the other issues.

**Comment by dakotabenjamin** [comment]
It's not deleting the dataset. Don't you have to rmdir(tmp_dir.c_str()) not out_dir?

**Comment by dakotabenjamin** [comment]
```
    /* Remove temporary files. */
    std::cout << "\tDeleting temporary data... " << std::endl;
    for (util::fs::File const & file : util::fs::Directory(tmp_dir))
    {
        std::cout << file.path + "/" + file.name << std::endl;
        util::fs::unlink((file.path + "/" + file.name).c_str());
    }
    util::fs::rmdir(tmp_dir.c_str());
    std::cout << "\tDone!" << std::endl;
```

You can delete the stdout if you want, this works for me

**Comment by nmoehrle** [comment]
You are absolutely right I'll change and merge it tomorrow :-) Thanks!

**Comment by nmoehrle** [comment]
Given my current record on the issue I would like get another OK from you before merging ;-)

**Comment by dakotabenjamin** [comment]
It works great now 😀

**Comment by nmoehrle** [comment]
Really appreciated your help - thank you!

**Pull request merged**
